import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/navbra/Navbar";
import Hero from "../components/hero/Hero"
import Description from "../components/description/Description";
import Products from "../components/products/Products";
import Contact from "../components/contact/Contact";
import Footer from "../components/footer/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navbar/>
        <Hero/>
        <Description/>
        <Products/>
        <Contact/>
        <Footer/>

    </div>
  )
}

export default Home
